version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  # Porta de gerenciamento
      - "5672:5672"    # Porta padrão do RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    image: luizc/api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  messaging:
    image: luizc/messaging
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

volumes:
  rabbitmq_data:
